#Peer's own IP and port
my_ip: 127.0.0.1
my_port: 23358

#Peer to connect to

peer_ip: 0.0.0.0
peer_port: 12345


# These options can be used to connect to the remote server
#peer_ip: 130.225.104.138
#peer_port: 5555